language: node_js
node_js:
- "stable"
cache:
directories:
- node_modules
script:
- npm start
- npm run build
deploy:
provider: pages
skip_cleanup: true
github_token: githu_token
local_dir: build
on:
branch: master